apiVersion: krm-catalog.github.io/v1
kind: ApiGroupSnapshotSpec
spec:
  groupNames: ["settings.svcat.k8s.io"]
  repoUrl: https://github.com/kyma-project/kyma
  strategy: githubSearch
status:
  howAdded: fetchedFromGithub
  lastModifiedDate: '2020-04-18'
  license: apache-2.0
