apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    description: Represents a CatalogSourceConfig.
    displayName: Catalog Source Config
  name: catalogsourceconfigs.operators.coreos.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.currentPhase.phase.name
    description: Current status of the CatalogSourceConfig
    name: Status
    type: string
  - JSONPath: .status.currentPhase.phase.message
    description: Message associated with the current status
    name: Message
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: operators.coreos.com
  names:
    kind: CatalogSourceConfig
    listKind: CatalogSourceConfigList
    plural: catalogsourceconfigs
    shortNames:
    - csc
    singular: catalogsourceconfig
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: CatalogSourceConfig is used to enable an operator present in the
        OperatorSource to your cluster. Behind the scenes, it will configure an OLM
        CatalogSource so that the operator can then be managed by OLM.
      properties:
        spec:
          description: Spec for a CatalogSourceConfig
          properties:
            csDisplayName:
              description: DisplayName is passed along to the CatalogSource to be
                used as a pretty name.
              type: string
            csPublisher:
              description: It represents the entity that published the operator(s)
                specified in packages.
              type: string
            packages:
              description: Comma separated list of operator(s) without spaces which
                will be enabled in the target namespace
              type: string
            source:
              description: The name of the OperatorSource that the packages originate
                from
              pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
              type: string
            targetNamespace:
              description: The namespace where the operators will be enabled
              type: string
          required:
          - targetNamespace
          - packages
          - source
          type: object
        status:
          type: object
  version: v2
  versions:
  - name: v2
    served: true
    storage: true
  - name: v1
    served: true
    storage: false
