apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    description: Represents a plan to install and resolve dependencies for Cluster
      Services
    displayName: Install Plan
  name: installplans.operators.coreos.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.clusterServiceVersionNames[0]
    description: The first CSV in the list of clusterServiceVersionNames
    name: CSV
    type: string
  - JSONPath: .spec.source
    description: The catalog source for the specified CSVs.
    name: Source
    type: string
  - JSONPath: .spec.approval
    description: The approval mode
    name: Approval
    type: string
  - JSONPath: .spec.approved
    name: Approved
    type: boolean
  group: operators.coreos.com
  names:
    categories:
    - olm
    kind: InstallPlan
    listKind: InstallPlanList
    plural: installplans
    shortNames:
    - ip
    singular: installplan
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Represents a plan to install and resolve dependencies for Cluster
        Services.
      properties:
        spec:
          anyOf:
          - properties:
              approval:
                enum:
                - Manual
              approved:
                type: boolean
            required:
            - approved
          - properties:
              approval:
                enum:
                - Automatic
          description: Spec for an InstallPlan
          properties:
            clusterServiceVersionNames:
              description: A list of the names of the Cluster Services
              items:
                type: string
              type: array
            source:
              description: Name of the preferred CatalogSource
              type: string
            sourceNamespace:
              description: Namespace that contains the preffered CatalogSource
              type: string
          required:
          - clusterServiceVersionNames
          - approval
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
