apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: operatorgroups.operators.coreos.com
spec:
  group: operators.coreos.com
  names:
    categories:
    - olm
    kind: OperatorGroup
    listKind: OperatorGroupList
    plural: operatorgroups
    shortNames:
    - og
    singular: operatorgroup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: A grouping of namespaces for usage with an operator.
      properties:
        spec:
          description: Spec for an OperatorGroup.
          properties:
            selector:
              anyOf:
              - properties:
                  matchLabels:
                    description: Label key:value pairs to match directly
                    type: object
                required:
                - matchLabels
              - properties:
                  matchExpressions:
                    description: A set of expressions to match against the resource.
                    items:
                      allOf:
                      - properties:
                          key:
                            description: the key to match
                            type: string
                          operator:
                            description: the operator for the expression
                            enum:
                            - In
                            - NotIn
                            - Exists
                            - DoesNotExist
                            type: string
                          values:
                            description: set of values for the expression
                            type: array
                        required:
                        - key
                        - operator
                        - values
                        type: object
                    type: array
                required:
                - matchExpressions
              description: Optional label selector to find resources associated with
                or managed by the operator
              type: object
            serviceAccountName:
              type: string
            staticProvidedAPIs:
              description: If true, OLM will not modify the OperatorGroup's providedAPIs
                annotation.
              type: boolean
            targetNamespaces:
              description: Optional list of target namespaces. If set, OLM will ignore
                selector.
              items:
                pattern: ^\S+$
                type: string
              type: array
          type: object
        status:
          description: The status of the OperatorGroup.
          properties:
            lastUpdated:
              format: date-time
              type: string
            namespaces:
              items:
                type: string
              type: array
          required:
          - lastUpdated
          type: object
      required:
      - metadata
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  - name: v1alpha2
    served: true
    storage: false
