apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: installs.jenkins.io
spec:
  group: jenkins.io
  names:
    kind: Install
    plural: installs
    singular: install
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: true
