apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: my-cluster
  git:
    policyDir: hello-namespace/config-root
    secretType: ssh
    syncBranch: main
    syncRepo: git@github.com:<GITHUB-USERNAME>/anthos-config-management-samples.git
