apiVersion: events.cloud.google.com/v1alpha1
kind: CloudSchedulerSource
metadata:
  name: scheduler-test
spec:
  data: my test data
  location: us-central1
  schedule: '* * * * *'
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
