apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: clusterbundles.bundle.gke.io
spec:
  group: bundle.gke.io
  names:
    kind: ClusterBundle
    plural: clusterbundles
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            componentFiles:
              items:
                properties:
                  hash:
                    type: string
                  url:
                    type: string
                type: object
              type: array
            components:
              items:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  metadata:
                    type: object
                  spec:
                    properties:
                      clusterObjectFiles:
                        items:
                          properties:
                            hash:
                              type: string
                            url:
                              type: string
                          type: object
                        type: array
                      clusterObjects:
                        items:
                          type: object
                        type: array
                      rawTextFiles:
                        items:
                          properties:
                            hash:
                              type: string
                            url:
                              type: string
                          type: object
                        type: array
                      version:
                        type: string
                    type: object
                type: object
              type: array
            version:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []
