apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: valid-rule
spec:
  actions:
  - handler: handler-for-valid-rule
    instances:
    - instance-for-valid-rule
  match: request.headers["clnt"] == "abc"
