apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    tectonic-operators.coreos.com/upgrade-behaviour: CreateOrUpgrade
    tectonic-operators.coreos.com/upgrade-strategy: Patch
  name: clusters.multicluster.coreos.com
spec:
  group: multicluster.coreos.com
  names:
    kind: Cluster
    plural: clusters
    singular: cluster
  scope: Cluster
  version: v1
