apiVersion: krm-catalog.github.io/v1
kind: ApiGroupSnapshotSpec
spec:
  groupNames: ["xgboostjob.kubeflow.org"]
  repoUrl: https://github.com/kubeflow/xgboost-operator
  strategy: manual
status:
  howAdded: original
  lastModifiedDate: 2019-10-20
  license: apache-2.0
