apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    registry.cloud.google.com/eventTypes: "[\n  { \"type\": \"com.google.cloud.pubsub.topic.publish\"\
      , \"description\": \"This event is sent when a message is published to a Cloud\
      \ Pub/Sub topic.\"}\n]\n"
  name: pullsubscriptions.pubsub.cloud.google.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="Ready")].status
    name: Ready
    type: string
  - JSONPath: .status.conditions[?(@.type=="Ready")].reason
    name: Reason
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: pubsub.cloud.google.com
  names:
    categories:
    - all
    - knative
    - pubsub
    kind: PullSubscription
    plural: pullsubscriptions
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            ackDeadline:
              description: The default maximum time after a subscriber receives a
                message before the subscriber should acknowledge the message. Defaults
                to `30s`. Valid time units are `s`, `m`, `h`. The minimum deadline
                you can specify is 0 seconds. The maximum deadline you can specify
                is 600 seconds (10 minutes).
              type: string
            ceOverrides:
              description: Defines overrides to control modifications of the event
                sent to the sink.
              properties:
                extensions:
                  description: Extensions specify what attribute are added or overridden
                    on the outbound event. Each `Extensions` key-value pair are set
                    on the event as an attribute extension independently.
                  type: object
              type: object
            mode:
              description: Mode defines the encoding and structure of the payload
                of when this PullSubscription invokes the sink. Default is CloudEventsBinary.
              enum:
              - CloudEventsBinary
              - CloudEventsStructured
              - PushCompatible
              type: string
            project:
              description: ID of the Google Cloud Project that the Pub/Sub Topic exists
                in. E.g. 'my-project-1234' rather than its display name, 'My Project'
                or its number '1234567890'.
              type: string
            retainAckedMessages:
              description: Whether to retain acknowledged messages. If true, acknowledged
                messages will not be expunged until they fall out of the RetentionDuration
                window.
              type: boolean
            retentionDuration:
              description: How long to retain messages in backlog, from the time of
                publish. If retainAckedMessages is true, this duration affects the
                retention of acknowledged messages, otherwise only unacknowledged
                messages are retained. Defaults to 7 days (`168h`). Cannot be longer
                than 7 days or shorter than 10 minutes. Valid time units are `s`,
                `m`, `h`.
              type: string
            secret:
              description: Credential to use to poll the Cloud Pub/Sub Subscription.
                It is not used to create or delete the Subscription, only to poll
                it. The value of the secret entry must be a service account key in
                the JSON format (see https://cloud.google.com/iam/docs/creating-managing-service-account-keys).  Defaults
                to secret.name of 'google-cloud-key' and secret.key of 'key.json'.
              type: object
            sink:
              description: Reference to an object that will resolve to a domain name
                to use as the sink.
              type: object
            topic:
              description: ID of the Cloud Pub/Sub Topic to Subscribe to. It must
                be in the form of the unique identifier within the project, not the
                entire name. E.g. it must be 'laconia', not 'projects/my-gcp-project/topics/laconia'.
              type: string
            transformer:
              description: Reference to an object that will resolve to a domain name
                to use as the transformer.
              type: object
          required:
          - sink
          - topic
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            observedGeneration:
              format: int64
              type: integer
            projectId:
              type: string
            sinkUri:
              type: string
            subscriptionId:
              type: string
            transformerUri:
              type: string
          type: object
  version: v1alpha1
