apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceplans.broker.istio.io
spec:
  group: broker.istio.io
  names:
    kind: ServicePlan
    plural: serviceplans
    singular: serviceplan
  scope: Namespaced
  version: dev
