apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceclasses.broker.istio.io
spec:
  group: broker.istio.io
  names:
    kind: ServiceClass
    plural: serviceclasses
    singular: serviceclass
  scope: Namespaced
  version: dev
