apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: condtional-pr
spec:
  pipelineRef:
    name: conditional-pipeline
  resources:
  - name: source-repo
    resourceRef:
      name: pipeline-git
  serviceAccountName: default
