apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: '1.0'
  name: releasetracks.app.gke.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.applicationRef.name
    description: The name of the application managed by the ReleaseTrack
    name: App
    type: string
  - JSONPath: .spec.version
    description: The desired version of the application managed by the ReleaseTrack
    name: Desired
    type: string
  - JSONPath: .status.currentVersion
    description: The current version of the application managed by the ReleaseTrack
    name: Current
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: app.gke.io
  names:
    kind: ReleaseTrack
    plural: releasetracks
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            applicationRef:
              description: '`applicationRef` is a reference to an Application object
                in the same namespace that will include the information about the
                application and will be used as the root/owner object referenced by
                all resources related to the application, including this ReleaseTrack
                object.'
              type: object
            deadlineSeconds:
              description: The duration in seconds relative to the time when the controller
                starts the actuation of the desired application state (via an installation
                or upgrade), before the controller gives up and actively terminates
                it. By default, no deadline is set.
              format: int64
              minimum: 0
              type: integer
            digest:
              description: '`digest` is the digest of the application manifest. Digest
                is a content-addressable identifier and can be used in addition to
                `version` to validate the application manifest to download.'
              type: string
            name:
              description: '`name` is the uniquely identifiable name of the application
                manifest to retrieve from the repository. This field will be ignored
                for "Deployer" format repository.'
              type: string
            revisionHistoryLimit:
              description: The number of revision history objects (i.e. ControllerRevisions)
                to retain to allow rollback. If not specified, 10 most recent ControllerRevision
                objects will be kept.
              format: int32
              type: integer
            serviceAccountName:
              description: '`serviceAccountName` is the service account used for launching
                the application.'
              type: string
            sourceRepository:
              description: '`sourceRepository` is a repository that houses application
                manifests.'
              properties:
                secretRef:
                  description: '`secretRef` is an optional reference to a secret in
                    the same namespace to be used for connecting to the repository.'
                  type: object
                type:
                  description: '`type` indicates the type of the repository. Currently,
                    this can be "Helm", "Deployer" or "Git".'
                  enum:
                  - Helm
                  - Deployer
                  - Git
                  type: string
                url:
                  description: '`url` resolves to a repository that houses application
                    manifests.'
                  minLength: 1
                  type: string
              required:
              - type
              - url
              type: object
            values:
              description: '`values` is a string containing (unparsed) JSON data for
                declaring parameter values to customize the application. The value
                must be able to be serialized to JSON format. This is only used when
                referencing a "Helm" format Repository.'
              type: string
            valuesSecretRef:
              description: '`valuesSecretRef` is an optional reference to a Secret
                in the same namespace containing data for declaring parameter values
                to customize the application. This is only used when referencing a
                "Deployer" format Repository.'
              type: object
            version:
              description: '`version` is the version of the application manifest.
                The version needs to follow SemVer 2 guidelines (in MAJOR.MINOR.PATCH
                format).'
              minLength: 1
              type: string
          required:
          - sourceRepository
          - version
          - applicationRef
          type: object
        status:
          properties:
            availableVersions:
              description: '`availableVersions` lists all available versions of this
                application manifest discovered from the repository.'
              items:
                properties:
                  deprecated:
                    description: '`deprecated` is a flag that tells whether this release
                      has been deprecated.'
                    type: boolean
                  digest:
                    description: '`digest` is the checksum of the artifact, either
                      a helm chart or a deployer'
                    type: string
                  name:
                    description: '`name` is the name of the application.'
                    type: string
                  recommended:
                    description: '`recommended` is a flag that tells whether this
                      is a recommended update'
                    type: boolean
                  releaseDate:
                    description: '`releaseDate` is the date on which this release
                      became available.'
                    format: date-time
                    type: string
                  releaseNote:
                    description: '`releaseNote` is information about this release.'
                    type: string
                  releaseType:
                    description: '`releaseType` is the type of release. This can be
                      either Feature, BugFix or Security.'
                    items:
                      enum:
                      - Feature
                      - BugFix
                      - Security
                      type: string
                    type: array
                  version:
                    description: '`version` is the version of this release the application.'
                    type: string
                required:
                - name
                - version
                type: object
              type: array
            conditions:
              description: '`conditions` represents the latest observations of a ReleaseTrack''s
                current state.'
              items:
                properties:
                  lastTransitionTime:
                    description: Last time this condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of ReleaseTrack condition.
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            currentReleaseTrackRevision:
              description: '`currentReleaseTrackRevision` is the current revision
                number of the ReleaseTrack spec.'
              format: int64
              type: integer
            currentVersion:
              description: '`currentVersion` is the current version of the application
                manifest that has been launched.'
              type: string
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []
