apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: filtering-type-and-source
spec:
  filter:
    sourceAndType:
      source: dev.knative.bar
      type: dev.knative.foo
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: message-dumper
