apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appdbs.ctl.isla.solutions
spec:
  group: ctl.isla.solutions
  names:
    kind: AppDB
    plural: appdbs
    shortNames:
    - appdb
    singular: appdb
  scope: Namespaced
  version: v1
