apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appdbinstances.ctl.isla.solutions
spec:
  group: ctl.isla.solutions
  names:
    kind: AppDBInstance
    plural: appdbinstances
    shortNames:
    - appdbi
    singular: appdbinstance
  scope: Namespaced
  version: v1
