apiVersion: krm-catalog.github.io/v1
kind: ApiGroupSnapshotSpec
spec:
  groupNames: ["ctl.isla.solutions"]
  repoUrl: https://github.com/danisla/terraform-operator
  strategy: manual
status:
  howAdded: original
  lastModifiedDate: 2019-10-20
  license: apache-2.0
