apiVersion: krm-catalog.github.io/v1
kind: ApiGroupSnapshotSpec
spec:
  groupNames: ["config.gatekeeper.sh"]
  repoUrl: https://github.com/open-policy-agent/gatekeeper
  strategy: manual
status:
  howAdded: original
  lastModifiedDate: 2019-10-20
  license: apache-2.0
