apiVersion: krm-catalog.github.io/v1
kind: ApiGroupSnapshotSpec
spec:
  groupNames: ["monitoring.coreos.com"]
  repoUrl: https://github.com/deepigopi/fuse
  strategy: manual
status:
  howAdded: original
  lastModifiedDate: 2019-10-20
  license: apache-2.0
