apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rbacdefinitions.rbacmanager.reactiveops.io
spec:
  group: rbacmanager.reactiveops.io
  names:
    kind: RBACDefinition
    plural: rbacdefinitions
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        rbacBindings:
          items:
            properties:
              clusterRoleBindings:
                items:
                  properties:
                    clusterRole:
                      type: string
                  required:
                  - clusterRole
                  type: object
                type: array
              name:
                type: string
              roleBindings:
                items:
                  properties:
                    clusterRole:
                      type: string
                    namespace:
                      type: string
                    namespaceSelector:
                      properties:
                        matchExpressions:
                          type: array
                        matchLabels:
                          type: object
                      type: object
                    role:
                      type: string
                  type: object
                type: array
              subjects:
                items:
                  type: object
                type: array
            required:
            - name
            - subjects
            type: object
          type: array
        status:
          type: object
      required:
      - metadata
      - rbacBindings
      type: object
  version: v1beta1
