apiVersion: krm-catalog.github.io/v1
kind: ApiGroupSnapshotSpec
spec:
  groupNames: ["operator.knative.dev"]
  repoUrl: https://github.com/matzew/kafka-source-operator
  strategy: manual
status:
  howAdded: original
  lastModifiedDate: 2019-10-20
  license: apache-2.0
