apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: gameserverallocationpolicies.multicluster.agones.dev
spec:
  group: multicluster.agones.dev
  names:
    kind: GameServerAllocationPolicy
    plural: gameserverallocationpolicies
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            connectionInfo:
              properties:
                allocationEndpoints:
                  items:
                    type: string
                  minItems: 1
                  type: array
                clusterName:
                  type: string
                namespace:
                  type: string
                secretName:
                  type: string
              required:
              - namespace
              type: object
            priority:
              format: int64
              minimum: 0
              type: integer
            weight:
              format: int64
              minimum: 0
              type: integer
          required:
          - priority
          - weight
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []
