apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: addressableservices.samples.knative.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .status.address.url
    name: Address
    type: string
  - JSONPath: .status.conditions[?(@.type=='Ready')].status
    name: Ready
    type: string
  - JSONPath: .status.conditions[?(@.type=='Ready')].reason
    name: Reason
    type: string
  group: samples.knative.dev
  names:
    categories:
    - all
    - knative
    kind: AddressableService
    plural: addressableservices
    shortNames:
    - asvc
    singular: addressableservice
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
