apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: natsstreamingclusters.streaming.nats.io
spec:
  group: streaming.nats.io
  names:
    kind: NatsStreamingCluster
    listKind: NatsStreamingClusterList
    plural: natsstreamingclusters
    shortNames:
    - stanclusters
    - stancluster
    singular: natsstreamingcluster
  scope: Namespaced
  version: v1alpha1
