apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: policies.getambassador.io
spec:
  group: getambassador.io
  names:
    kind: Policy
    plural: policies
    shortNames:
    - pol
    singular: policy
  scope: Namespaced
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
