apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: kubernetesendpointresolvers.getambassador.io
spec:
  group: getambassador.io
  names:
    kind: KubernetesEndpointResolver
    plural: kubernetesendpointresolvers
    singular: kubernetesendpointresolver
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
