apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: consulresolvers.getambassador.io
spec:
  group: getambassador.io
  names:
    kind: ConsulResolver
    plural: consulresolvers
    singular: consulresolver
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
