apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: modules.getambassador.io
  namespace: beta
spec:
  group: getambassador.io
  names:
    categories:
    - ambassador-crds
    kind: Module
    plural: modules
    singular: module
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
