apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tracingservices.getambassador.io
  namespace: beta
spec:
  group: getambassador.io
  names:
    categories:
    - ambassador-crds
    kind: TracingService
    plural: tracingservices
    singular: tracingservice
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
