apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tenants.tenants.k8s.io
spec:
  group: tenants.k8s.io
  names:
    kind: Tenant
    plural: tenants
    singular: tenant
  scope: Cluster
  versions:
  - name: v1alpha1
    served: true
    storage: true
