apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterservicebrokers.servicecatalog.k8s.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.url
    name: URL
    type: string
  - JSONPath: .status.lastConditionState
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: servicecatalog.k8s.io
  names:
    categories:
    - all
    - svcat
    kind: ClusterServiceBroker
    plural: clusterservicebrokers
    singular: clusterservicebroker
  scope: Cluster
  subresources:
    status: {}
  version: v1beta1
