apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicebindings.servicecatalog.k8s.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.instanceRef.name
    name: Service-Instance
    type: string
  - JSONPath: .spec.secretName
    name: Secret-Name
    type: string
  - JSONPath: .status.lastConditionState
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: servicecatalog.k8s.io
  names:
    categories:
    - all
    - svcat
    kind: ServiceBinding
    plural: servicebindings
    singular: servicebinding
  scope: Namespaced
  subresources:
    status: {}
  version: v1beta1
