apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterserviceclasses.servicecatalog.k8s.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.externalName
    name: External-Name
    type: string
  - JSONPath: .spec.clusterServiceBrokerName
    name: Broker
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: servicecatalog.k8s.io
  names:
    categories:
    - all
    - svcat
    kind: ClusterServiceClass
    plural: clusterserviceclasses
    singular: clusterserviceclass
  scope: Cluster
  subresources:
    status: {}
  version: v1beta1
