apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceplans.servicecatalog.k8s.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.externalName
    name: External-Name
    type: string
  - JSONPath: .spec.serviceBrokerName
    name: Broker
    type: string
  - JSONPath: .spec.serviceClassRef.Name
    name: Class
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: servicecatalog.k8s.io
  names:
    categories:
    - all
    - svcat
    kind: ServicePlan
    plural: serviceplans
    singular: serviceplan
  scope: Namespaced
  subresources:
    status: {}
  version: v1beta1
