apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceinstances.servicecatalog.k8s.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.userSpecifiedClassName
    name: Class
    type: string
  - JSONPath: .status.userSpecifiedPlanName
    name: Plan
    type: string
  - JSONPath: .status.lastConditionState
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: servicecatalog.k8s.io
  names:
    categories:
    - all
    - svcat
    kind: ServiceInstance
    plural: serviceinstances
    singular: serviceinstance
  scope: Namespaced
  subresources:
    status: {}
  version: v1beta1
