apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventactivations.applicationconnector.kyma-project.io
spec:
  group: applicationconnector.kyma-project.io
  names:
    kind: EventActivation
    plural: eventactivations
    shortNames:
    - ea
    singular: eventactivation
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            displayName:
              type: string
            sourceId:
              maxLength: 253
              minLength: 1
              pattern: ^[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?)*$
              type: string
  version: v1alpha1
