apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: groups.authentication.kyma-project.io
spec:
  group: authentication.kyma-project.io
  names:
    kind: Group
    plural: groups
    shortNames:
    - grp
    singular: group
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            description:
              maxLength: 256
              type: string
            idpName:
              maxLength: 32
              type: string
            name:
              maxLength: 64
              type: string
          required:
          - idpName
          - name
          type: object
  version: v1alpha1
