apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: idppresets.authentication.kyma-project.io
spec:
  group: authentication.kyma-project.io
  names:
    kind: IDPPreset
    plural: idppresets
    shortNames:
    - idp
    singular: idppreset
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            issuer:
              minLength: 1
              type: string
            jwksUri:
              minLength: 1
              pattern: ^(https?)://.+$
              type: string
          required:
          - issuer
          - jwksUri
          type: object
      required:
      - spec
  version: v1alpha1
