apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  name: compassconnections.compass.kyma-project.io
spec:
  group: compass.kyma-project.io
  names:
    kind: CompassConnection
    listKind: CompassConnectionList
    plural: compassconnections
    singular: compassconnection
  scope: Cluster
  version: v1alpha1
