apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: subscriptions.eventing.kyma-project.io
spec:
  group: eventing.kyma-project.io
  names:
    kind: Subscription
    plural: subscriptions
    shortNames:
    - sub
    singular: subscription
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            endpoint:
              maxLength: 512
              pattern: ^(https?)://.+$
              type: string
            event_type:
              maxLength: 253
              minLength: 1
              pattern: ^[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?)*$
              type: string
            event_type_version:
              maxLength: 4
              minLength: 1
              pattern: ^[a-zA-Z0-9]+$
              type: string
            include_subscription_name_header:
              type: boolean
            source_id:
              maxLength: 253
              minLength: 1
              pattern: ^[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?)*$
              type: string
          required:
          - event_type
          - event_type_version
          - source_id
  version: v1alpha1
