apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicebindingusages.servicecatalog.kyma-project.io
spec:
  group: servicecatalog.kyma-project.io
  names:
    kind: ServiceBindingUsage
    plural: servicebindingusages
    shortNames:
    - sbu
    - svcbindingusage
    singular: servicebindingusage
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            parameters:
              properties:
                envPrefix:
                  properties:
                    name:
                      type: string
                  required:
                  - name
                  type: object
              type: object
            serviceBindingRef:
              properties:
                name:
                  type: string
              required:
              - name
              type: object
            usedBy:
              properties:
                kind:
                  type: string
                name:
                  type: string
              required:
              - kind
              - name
              type: object
  version: v1alpha1
