apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: remoteservicebindings.multicluster.istio.io
spec:
  group: multicluster.istio.io
  names:
    kind: RemoteServiceBinding
    listKind: RemoteServiceBindingList
    plural: remoteservicebindings
    singular: remoteservicebinding
  scope: Namespaced
  version: v1alpha1
