apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceexpositionpolicies.multicluster.istio.io
spec:
  group: multicluster.istio.io
  names:
    kind: ServiceExpositionPolicy
    listKind: ServiceExpositionPolicyList
    plural: serviceexpositionpolicies
    singular: serviceexpositionpolicy
  scope: Namespaced
  version: v1alpha1
