apiVersion: krm-catalog.github.io/v1
kind: ApiGroupSnapshotSpec
spec:
  groupNames: ["app.k8s.io"]
  repoUrl: https://github.com/cliveseldon/marketplace-k8s-app-tools
  strategy: manual
status:
  howAdded: original
  lastModifiedDate: 2019-10-20
  license: apache-2.0
